### ISSUE TITLE
Uncertain naming: Phoenix?

### ISSUE THREAD

**Issue by arboud15** [homermultitext/hmt-authlists#215]
There's only one Phoenix in the table, described as the relative of Europa. But the Phoenix in the Iliad is a different person. Are the occurrences of Phoenix so far marked wrong? Should we change the description? Has Phoenix (the one related to Europa) come up in the manuscript?

**Comment by StephanieML** [comment]
In the archive, the only place Phoenix has appeared in the scholia is the one we have in our table, so that reference is correct.

**Comment by StephanieML** [comment]
The Phoenix references in Iliad 9 main text will be wrong and should be fixed

**Comment by StephanieML** [comment]
I'm going to reject our current one and enter both Phoenixes as new references so eventually when these books are validated they can be fixed

**Comment by StephanieML** [comment]
resolved
