### ISSUE TITLE
Possible duplication: Euphorion

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-authlists#236]
The Auth list gives two different Euphorions, both of whom are grammarians. Wikipedia leads us to believe that they may be the same person....not sure. We are using the more complete entry

**Comment by StephanieML** [comment]
ok, for now, use the second entry because it has the most detail, I will at some point investigate the archive to see if we should reject the first entry and combine with the second.

**Comment by StephanieML** [comment]
interestingly the first urn doesn't show up in the archive of 1-10 scholia. Maybe the Venetus B team used it? But I think they the same person so I'm going to reject the first one and redirect to the second one.

**Comment by StephanieML** [comment]
resolved
