### ISSUE TITLE
new placeName: Kos urn:cite:hmt:msA.185v

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-authlists#241]
passage - urn:cts:greekLit:tlg5026:msA:14.H1

Kos -  island of the group of the Dodecanese in Caria, also spelled Kos

**Comment by StephanieML** [comment]
is it not urn:cite:hmt:place.place68?

**Comment by brclar15** [comment]
http://encyclopedia2.thefreedictionary.com/K%C3%B3s

hmm i dont think 68 is correct.....awk

**Comment by StephanieML** [comment]
I'm inclined to think 68 is ok, just because it's so specific. There have been times when we run into place names in the scholia that have no other record and have the same name as other places. I will add a second Cos though.

added as urn:cite:hmt:place.place430
