### ISSUE TITLE
new persName: urn:cite:hmt:msA.187v Euphranor 

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-authlists#243]
Passage: urn:cts:greekLit:tlg5026.msA:14.A9

Euphranor - je ne sais pas.....   there was an artist with that name, but we don't think this scholion is referring to him. Could just be an obscure grammarian? δεν ξερω.....

**Comment by StephanieML** [comment]
Ok, so my digging, has turned up a Euphranor who was an obscure grammarian. One of his pupils was Apion who was noted as a Homerist. I found a reference to him in the Suda, so I'm pretty convinced.

**Comment by StephanieML** [comment]
added as urn:cite:hmt:pers.pers927
