### ISSUE TITLE
New persNames: Satnius and Enops urn:cite:hmt:msA.189r

### ISSUE THREAD

**Issue by arboud15** [homermultitext/hmt-authlists#244]
Satnius: urn:cts:greekLit:tlg0012.tlg001:msA.14.443
Enops: urn:cts:greekLit:tlg0012.tlg001:msA:14.445

Satnius: son of Enops and a nymph, slain by Ajax the lesser
Enops: father of Satnius and Thestor, married nymph Satnioeis

**Comment by StephanieML** [comment]
Satnius is urn:cite:hmt:pers.pers908
Enops is urn:cite:hmt:pers.pers909
