### ISSUE TITLE
new persName: Morys & Hippotion urn:cite:hmt:msA.190v

### ISSUE THREAD

**Issue by arboud15** [homermultitext/hmt-authlists#252]
passage: urn:cts:greekLit:tlg0012.tlg001:msA:14.514

Morys - a Mysian, the son of Hippotion, slain by Meriones

Hippotion - an Ascanian, slain by Meriones

**Comment by StephanieML** [comment]
added as urn:cite:hmt:pers.pers917 and urn:cite:hmt:pers.pers918
