### ISSUE TITLE
new persName: Prothoon & Periphetes urn:cite:hmt:msA.190v

### ISSUE THREAD

**Issue by arboud15** [homermultitext/hmt-authlists#253]
passage: urn:cts:greekLit:tlg0012.tlg001:msA:14.515

Prothoon - a Trojan, slain by Teucer

Periphetes - a Mysian, slain by Teucer

**Comment by StephanieML** [comment]
added as urn:cite:hmt:pers.pers919 and urn:cite:hmt:pers.pers920
