### ISSUE TITLE
New Place for group Myrmidons

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/hmt-authlists#256]
16.39 First word μυρμιδόνων is an ethnic group which does not have a place to use as a reference in the XML.

**Comment by JaneyCapers** [comment]
Some sources say the Myrmidons are from Phthia. Would this be the place we'd use?

**Comment by JaneyCapers** [comment]
We found "ethnic adjectives Use TEI rs element. Include a @type attribute with value ethnic, and @n attributewith an identifier from the reference table for place names⁸." in the editor's guide, so we used the place names/references.
ex. <rs type="ethnic" n="urn:cite:hmt:place.place114">ἀργείοισιν</rs>

**Comment by StephanieML** [comment]
We don't do any mark up for Myrmidons.
