### ISSUE TITLE
new persName: urn:cite:hmt:msA.186v Dictys Polydectes

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-authlists#260]
passage: urn:cts:greekLit:tlg5026:msA.14.H29

Dictys - fisherman and brother of King Polydectes of Seriphos, discovered Danaë and Perseus inside a chest

Polydectes - king of Seriphos, turned to stone by Perseus

**Comment by StephanieML** [comment]
added as urn:cite:hmt:pers.pers925 and urn:cite:hmt:pers.pers926
