### ISSUE TITLE
new pers/place name

### ISSUE THREAD

**Issue by amiegoblirsch** [homermultitext/hmt-authlists#263]
I found the proper noun Εὐχήνορα In the main scholia referring to line 13.659. I don't know if it is a pers or place name but either way we have no proper noun tag for it as of yet. 
this is what the whole scholia says. 
ἐπεὶ ὁ Ἀλέξανδρος χαλεπήνας, ὑπερ τοῦ ἀνηρημενου Εὐχήνορα τὸν Κορίνθιου ἀναιρεῖ⁑

**Comment by brclar15** [comment]
added as urn:cite:hmt:pers.pers939
