### ISSUE TITLE
New PersName: Arcesilaus urn:cite:hmt:msA.197v

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/hmt-authlists#268]
Arcesilaus is a soldier slain by Hector. urn:cts:greekLit:tlg0012.tlg001.msA:15.329

**Comment by cjschu17** [comment]
Comrade of Menestheus

**Comment by StephanieML** [comment]
already exists urn:cite:hmt:pers.pers348, will add these to his descriptor
