### ISSUE TITLE
New persName: Pyrithlegethon urn:cite:hmt:msA.249r

### ISSUE THREAD

**Issue by scnevi17** [homermultitext/hmt-authlists#288]
Pyrithlegethon: one of the rivers in the underworld

urn:cts:greekLit:tlg5026:msA.hmt:18.186

**Comment by StephanieML** [comment]
is it a persName, personification of the river? or placeName geographic location?

**Comment by brclar15** [comment]
after reading the scholion, and consulting with the Nev-dawg and A-baby, it has been added as urn:cite:hmt:place.place440
