### ISSUE TITLE
New persName urn:cite:hmt:msA.248v

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/hmt-authlists#289]
Pre-Socratic philosopher from Miletus in Asia Minor; one of the Seven Sages.

urn:cts:greekLit:tlg5026.msA.hmt:170

**Comment by brclar15** [comment]
akw, I need to know who it is..........the name, I need a name, I've got nothing on the name!

**Comment by mwauke** [comment]
It's Thales

**Comment by brclar15** [comment]
your face is Thales.

added as urn:cite:hmt:pers.pers1029
