### ISSUE TITLE
Question on tagging the Areopagus

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-authlists#290]
Should the Areopagus be tagged as its own place, or is it like the Scaean gate which we do not tag?

urn:cts:greekLit:tlg5026.msA:hmt:18.174

**Comment by StephanieML** [comment]
I think we debated it before and decided not to; I can bring it up in our discussion with the editors

**Comment by StephanieML** [comment]
but I would lean towards, it's part of a city, and the city/town/etc is the smallest unit we go. like we had the term for the Acropolis in Troy and we decided to skip that as well last year

**Comment by brclar15** [comment]
agreed. Closing this until another decision is made
