### ISSUE TITLE
New persName: Afidnes urn:cite:hmt:msA.250v

### ISSUE THREAD

**Issue by arsimr16** [homermultitext/hmt-authlists#294]
Afidnes: one of the twelve ancient towns of Attica; the place where Theseus left Helen after he had abducted her.

urn:cts:greekLit:tlg5026.msA.hmt:18.214

**Comment by StephanieML** [comment]
called Aphidnes in modern Greek, but Aphidna in Ancient Greek so will be entered as Aphidna

**Comment by StephanieML** [comment]
also please remember to title the issue as placeName, when it is indeed a place name

**Comment by StephanieML** [comment]
added as urn:cite:hmt:place.place442
