### ISSUE TITLE
New Persname: Erinys urn:cite:hmt:msA253r

### ISSUE THREAD

**Issue by ulalian** [homermultitext/hmt-authlists#297]
Erinys: one of the multiple personifications of curses pronounced upon a guilty crime; they are reckoned among those who inhabit Erebus, where they rest until some curse pronounced upon a criminal calls them to life and activity. 

urn:cts:greekLit:tlg0012.tlg001.msA:19.87

**Comment by StephanieML** [comment]
urn:cite:hmt:pers.pers1034
