### ISSUE TITLE
New persName:  Atê urn:cite:hmt:msA253r

### ISSUE THREAD

**Issue by ulalian** [homermultitext/hmt-authlists#298]
Atê: daugher of Eris and Zeus she was the spirit of delusion, infatuation, blind folly, rash action and reckless impulse who led men down the path to ruin; having tricked Zeus she was hurled from Olympus and forever banished.

urn:cts:greekLit:tlg0012.tlg001.msA19.91

**Comment by StephanieML** [comment]
urn:cite:hmt:pers.pers1035
