### ISSUE TITLE
New PersName: urn:cite:hmt:msA.251v Μύρης 

### ISSUE THREAD

**Issue by JaneyCapers** [homermultitext/hmt-authlists#299]
Myrrha: is the mother of Adonis in Greek mythology. She was transformed into a myrrh tree after having had intercourse with her father and gave birth to Adonis as a tree. Although the tale of Adonis has Semitic roots, it is uncertain from where the myth of Myrrha emerged, though it was likely from Cyprus.

urn:cts:greekLit:tlf0012.tlg001.msA:19.6

**Comment by StephanieML** [comment]
urn:cite:hmt:pers.pers1036
