### ISSUE TITLE
Extent of astro tags

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-authlists#301]
Just a thought. 
We should to define how intense we're getting with these astro tags. 
Stars and constellations seem to make sense to me, in order to differentiate them from the mythological figures. 
Currently, we also have the astrological poles. Should that be tagged?
Planets? The Sun/Moon?
I think it'd be good to decide this all and spell it out somewhere

**Comment by StephanieML** [comment]
Initial thoughts, I think planets make sense. I think we should have to be clear doing the sun and moon that we're talking about the heavenly bodies vs mythological entities and that might be unclear in some instances.

**Comment by StephanieML** [comment]
that we might have to address when we get good examples

**Comment by neelsmith** [comment]
Criterion should be whether these are *named entities* -- "proper nouns" vs. "common nouns".

Yes, the line between those categories will always be a little fuzzy.

**Comment by neelsmith** [comment]
I'm going to close this out as a general discussion:  post issues for any specific occurrences that are not perfectly clear.
