### ISSUE TITLE
New persName urn:cite:hmt:msA.224r Phrontis

### ISSUE THREAD

**Issue by cjscan18** [homermultitext/hmt-authlists#309]
urn:cts:greekLit:tlg5026:msA.17.40

Phrontis: wife of Panthous and mother of Euphorbus and Hyperenor

**Comment by brclar15** [comment]
yoooo sorry to be a pain, but could you push up your scholia xml? That way I can check the scholia (though I trust you), and assign her a number
thanks!

**Comment by cjschu17** [comment]
It's not the scholia (sorry to bother you Brian). It's actually just in the main text. 

urn:cts:greekLit:tlg0012.tlg001.msA:17.40

**Comment by cjschu17** [comment]
Hope this finds you in a good mood!

**Comment by brclar15** [comment]
most happily added as urn:cite:hmt:pers.pers1061
