### ISSUE TITLE
New Persname: Mentes

### ISSUE THREAD

**Issue by cjscan18** [homermultitext/hmt-authlists#311]
urn:cts:greekLit:tlg0012.tlg001.msA:17.73

Mentes: In the Iliad, Mentes (Μέντης) is the name of the King of the Cicones.

In Book XVII of The Iliad, Apollo disguises himself as Mentes to encourage Hector to fight Menelaus

**Comment by brclar15** [comment]
ah that tricky Apollo.....

added as urn:cite:hmt:pers.pers1062
