### ISSUE TITLE
New persName: Deis urn:cite:hmt:msA.227v

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/hmt-authlists#314]
Another Trojan

urn:cts:greekLit:tlg0012.tlg001.msA:17.217

**Comment by brclar15** [comment]
could this be Deisenor the Lycian, instead of one Deis the Trojan?
just a thought.
it matches the URN that you gave me

**Comment by brclar15** [comment]
have we resolved this?

**Comment by zachsowerby** [comment]
Deisenor added as _urn:cite2:hmt:pers.v1:pers1258_

Thanks!
