### ISSUE TITLE
New persName: Phaenops urn:cite:hmt:msA.235r

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/hmt-authlists#320]
Son of Asius, grandson of Dymas and brother of Adamas. He was a resident of Abydus and the best guest-friend of Hector. Apollo, at one point, assumed the form of this Phaenops to appear in front of Hector

Not to confused with Phaenops, a Trojan, father of Xanthus and Thoon.

urn:cts:greekLit:tlg0012.tlg001.msA:17.583

**Comment by brclar15** [comment]
added as urn:cite:hmt:pers.pers1071
