### ISSUE TITLE
New persName: Antisthenes urn:cite:hmt:msA.294r

### ISSUE THREAD

**Issue by jamesp23** [homermultitext/hmt-authlists#323]
Philosopher, student of Socrates; argues that souls are human-shaped.

First main scholion of 294r.

**Comment by brclar15** [comment]
could you give me the URN for the line that the scholion is commenting on?
Thanks!

**Comment by jamesp23** [comment]
Certainly!

urn:cts:greekLit:tlg0012.tlg001.msA:23.65

**Comment by brclar15** [comment]
Thanks! 
In the future, it helps me a lot if you add the line URN at the bottom of your first comment.

He's added as urn:cite:hmt:pers.pers1072

Keep up the good work!
