### ISSUE TITLE
New persName: Clearchus urn:cite:hmt:msA.294r

### ISSUE THREAD

**Issue by jamesp23** [homermultitext/hmt-authlists#329]
Author of "Glosses"

urn:cts:greekLit:tlg0012.tlg001.msA:23.81

**Comment by brclar15** [comment]
Clearchus doesn't appear in the Iliad. The URN that you gave me is for the Iliadic text, not the scholia. If you give me the scholia URN, I'd be happy to add these for you.

Thanks!

**Comment by brclar15** [comment]
added as urn:cite2:hmt:pers:pers1129 from another issue
