### ISSUE TITLE
Place number for Naxos

### ISSUE THREAD

**Issue by olgalevaniouk** [homermultitext/hmt-authlists#331]

**Comment by brclar15** [comment]
Could you provide the urn for the passage where the name occurs, and what folio it appears on?

Thanks!

**Comment by olgalevaniouk** [comment]
294v.
Thank you!

Olga Levaniouk
Associate Professor, Classics
University of Washington
Seattle WA 98195

**Comment by brclar15** [comment]
added as urn:cite2:hmt:place:place451
