### ISSUE TITLE
New persName: Meriones urn:cite:hmt:msA.235v

### ISSUE THREAD

**Issue by mjkell18** [homermultitext/hmt-authlists#340]
urn:cts:greekLit:tlg5026:msA.17.608-616

Greek warrior, half-brother of Idomeneus, grandson of Deucalion

**Comment by mjkell18** [comment]
I just saw that Meriones is pers212 as "Merion." However, it seems he is more widely known by the name "Meriones," so should we change the name to Meriones?

**Comment by StephanieML** [comment]
we will keep the label and add meriones to the description so that both will be found when searched.
