### ISSUE TITLE
New personal name: Sosippus the comic, 292v

### ISSUE THREAD

**Issue by olgalevaniouk** [homermultitext/hmt-authlists#342]

**Comment by StephanieML** [comment]
Can we get a passage reference? what scholion is this in?

**Comment by olgalevaniouk** [comment]
Main scholion on line 1 of book 23, on 292v.
Here is the image urn: urn:cite:hmt:vaimg.VA292VN-0794@0.222,0.5773,0.226,0.0593

**Comment by brclar15** [comment]
added as urn:cite2:hmt:pers:pers1141
