### ISSUE TITLE
New PersName? Zenodotus (the pupil of?) Crates: urn:cite:hmt:msA.294r, main scholion. 

### ISSUE THREAD

**Issue by olgalevaniouk** [homermultitext/hmt-authlists#344]
urn:cite:hmt:vaimg.VA294RN-0464@0.194,0.7185,0.484,0.0248

I have never heard to this person, and am not sure how to understand Κρατήτιος - a pupil of Crates is just my first guess, but it does not seem to be the famous Alexandrian Zenodotus.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1259_

Thanks!
