### ISSUE TITLE
New PlaceName: Naxos, urn:cite:hmt:msA.294v, urn:cts:greekLit:tlg0012.tlg001.msA:23.92 

### ISSUE THREAD

**Issue by olgalevaniouk** [homermultitext/hmt-authlists#348]
Naxos, one of the Cycladic islands
urn:cite:hmt:vaimg.VA294VN-0796@0.562,0.1704,0.358,0.0195

**Comment by brclar15** [comment]
added as urn:cite2:hmt:place:place451
