### ISSUE TITLE
New persName (a second) Herodicus urn:cite:hmt:msA.164v

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#364]
urn:cts:greekLit:tlg5026.msA.hmt:13.019

"Grammarian, second century B.C., student of Crates of Mallos."
The Herodicus mentioned here is the grammarian (not urn:cite:hmt:pers.pers678, the "Greek athletic physician").

**Comment by brclar15** [comment]
added as urn:cite:hmt:pers.pers1091
