### ISSUE TITLE
New persName: Polyphemus, urn:cite:hmt:msA.168v

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#374]
urn:cts:greekLit:tlg5026:msA.13.233

A Κύκλωψ is mentioned, with a reference to Od. 9.292.
Hence, must be Polyphemus the cyclops. (Only the lapith is in the authoritylist).

**Comment by brclar15** [comment]
added as urn:cite2:hmt:pers:pers1135
