### ISSUE TITLE
New persName: Aristeas, urn:cite:hmt:msA.166v

### ISSUE THREAD

**Issue by Bijvoets** [homermultitext/hmt-authlists#376]
urn:cts:greekLit:tlg0012.tlg001.msA:13.137

In the fifth main scholion (starts with ὀλοοιτροχος) there is a list of names, which clearly includes Ἀριστέας (Aristeas), an unknown scholiast, who ought to be added to the hmt-authlists.

**Comment by brclar15** [comment]
added as urn:cite2:hmt:pers:pers1138
