### ISSUE TITLE
New placeName: Abioi 

### ISSUE THREAD

**Issue by OVRMonster** [homermultitext/hmt-authlists#382]
164R line 6 Ἀβίων - ethnic name probably a Scythian people 

urn:cts:greekLit:tlg0012.tlg001:13.6

**Comment by brclar15** [comment]
@StephanieML 

Do we tag these people? they dont seem to have an eponymous place, but may the river referenced in this wiki article?

https://de.wikipedia.org/wiki/Abioi

or just don't tag them like Myrmidons or something

**Comment by StephanieML** [comment]
I feel like we saw them before and decided not to... but I could be making that up

**Comment by StephanieML** [comment]
review the issue tracker

**Comment by brclar15** [comment]
nope, it's not there

**Comment by brclar15** [comment]
added as urn:cite2:hmt:place.v1:place471 

use the Abianos river for the ethnic group
