### ISSUE TITLE
New placeName: Lampsacus, urn:cite:hmt:msA.178v

### ISSUE THREAD

**Issue by sk00gle** [homermultitext/hmt-authlists#396]
urn:cts:greekLit:tlg0012.tlg001.msA:13.759

In the main scholion to this line (starting with the lemma καὶ ἄσιον ὑρτάκου υἱὸν), the scholiast references the city of Lampsacus, a city in the northern Troad.

**Comment by juliaspiegel** [comment]
Added as urn:cite2:hmt:place.2017a:place448.
