### ISSUE TITLE
New placeName: Rhyndacus, urn:cite:hmt:msA.178v

### ISSUE THREAD

**Issue by sk00gle** [homermultitext/hmt-authlists#397]
urn:cts:greekLit:tlg0012.tlg001.msA:13.759

In the main scholion to this line (starting with the lemma καὶ ἄσιον ὑρτάκου υἱὸν), the scholiast references the river Rhyndacus, a river in northwestern Anatolia now known as the Mustafakemalpaşa River.

**Comment by juliaspiegel** [comment]
Added as urn:cite2:hmt:place.2017a:place447.
