### ISSUE TITLE
Problem with duplicate entry

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-authlists#398]
urn:cite:hmt:pers.pers55	Philonome
urn:cite:hmt:pers.pers114	Polyboea	

these are the same person. need to fix that in the editions, and the authList

**Comment by neelsmith** [comment]
I'll file a separate issue in hmt-archive about the editions.

**Comment by zachsowerby** [comment]
In the persName authority list I have changed the status of Polyboea to "REJECTED" with a redirect to urn:cite2:hmt:pers.v1:pers55. As I found it, the description of urn:cite2:hmt:pers.v1:pers114 was "see Philonome" and the scholion in Book 1 in which they appear (urn:cts:greekLit:tlg5026.msA.va_dipl:1.38) also suggests that this is the best course of action.
