### ISSUE TITLE
New persName: Simois, urn:cite:hmt:msA.276r

### ISSUE THREAD

**Issue by mwauke** [homermultitext/hmt-authlists#399]
urn:cts:greekLit:tlg0012.tlg001.msA:21.307

Simois is a river and river god, just like Scamander.
The placeName for the Simois river is already added, however, in this context, Scamander is addressing his brother, Simois. If Scamander has both a place and pers name, then so should Simois.

**Comment by juliaspiegel** [comment]
Added as urn:cite2:hmt:pers.2017a:pers1108.
