### ISSUE TITLE
New PersName: Hermaeus urn:cite:hmt:msA.179v

### ISSUE THREAD

**Issue by sk00gle** [homermultitext/hmt-authlists#401]
main scholion to urn:cts:greekLit:tlg0012.tlg001.msA:13.791

Hermaeus Soter; Indo-Greek king of the Eucratid dynasty

**Comment by brclar15** [comment]
this is not the person being referenced in the scholion.  
It is being used as an example of the "αῖος" ending names. It appears to be an adjectival form of Hermes, and therefore does not get tagged. it should be quoted though, since its an example
