### ISSUE TITLE
New persName: Alcaena, 282v

### ISSUE THREAD

**Issue by zachsowerby** [homermultitext/hmt-authlists#406]
Hound of Actaeon

**Comment by juliaspiegel** [comment]
Need text passage.

**Comment by zachsowerby** [comment]
urn:cts:greekLit:tlg5026.msA.hmt:22.6

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:22.29

**Comment by juliaspiegel** [comment]
Added as urn:cite2:hmt:pers.2017a:pers1103
