### ISSUE TITLE
New persName: Actaeon, 282v

### ISSUE THREAD

**Issue by zachsowerby** [homermultitext/hmt-authlists#407]
Hunter eaten by his own dogs at the direction of an angry Artemis.

**Comment by juliaspiegel** [comment]
Need text passage.

**Comment by zachsowerby** [comment]
urn:cts:greekLit:tlg5026.msA.hmt:22.6

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:22.29

**Comment by juliaspiegel** [comment]
Added as urn:cite2:hmt:pers.2017a:pers1104
