### ISSUE TITLE
New persName: Aethon, 283r

### ISSUE THREAD

**Issue by zachsowerby** [homermultitext/hmt-authlists#409]
Pseudonym of Odysseus

**Comment by juliaspiegel** [comment]
Need text passage.

**Comment by zachsowerby** [comment]
urn:cts:greekLit:tlg5026.msA.hmt:22.14

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:22.51

**Comment by juliaspiegel** [comment]
Added as urn:cite2:hmt:pers.2017a:pers1106

**Comment by brclar15** [comment]
@juliaspiegel 
hi, just a question.... if it's a "Pseudonym of Odysseus", isn't it still Odysseus? Like Pairs vs Alexander, they're the same person. so if Aethon is just a different name for Odysseus, it would be the same person number, no?

havent looked at the context at all, just saw this

**Comment by juliaspiegel** [comment]
We discussed this with Smith.  He suggested that the character of Aethon is separate from the person of Odysseus.  His idea was that Odysseus should be distinguished from Aethon, who is a creation of Odysseus's speech.

Also, who is Pairs?  I couldn't find his persNumber.

The last sentence was typed by Claude.

**Comment by brclar15** [comment]
ah, well then it's settled! 

WOW i felt really attacked out of the blue for a moment. but since it's Claude, I'll take it as affection.

carry on your with your awesome work, and best of luck at the conference!

**Comment by juliaspiegel** [comment]
Thanks!  Have fun during the rest of the seminar.
