### ISSUE TITLE
New persName: Eubulus, 285v

### ISSUE THREAD

**Issue by zachsowerby** [homermultitext/hmt-authlists#412]
A 4th-century BC comic poet and playwright.

urn:cts:greekLit:tlg5026.msA.hmt:22.46

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:22.162

**Comment by juliaspiegel** [comment]
Added as urn:cite2:hmt:pers.2017a:pers1107

**Comment by zachsowerby** [comment]
Thank you very much!
