### ISSUE TITLE
New pesName: Philitas, 288r

### ISSUE THREAD

**Issue by zachsowerby** [homermultitext/hmt-authlists#415]
Philitas (also spelled Philetas) of Cos, 4th century BC scholar, poet, and royal tutor who authored a work on Homeric language.

Main scholion urn:cts:greekLit:tlg5026.msA.hmt:22.72
Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:22.308

**Comment by juliaspiegel** [comment]
Added as urn:cite2:hmt:pers.2017a:pers1117.

**Comment by zachsowerby** [comment]
Thank you!
