### ISSUE TITLE
Need to reject a proposed name: urn:cite2:hmt:pers:pers265 Alcman

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-authlists#422]
urn:cite2:hmt:pers:pers265 Alcman as one of the Epigenoi

Ineke pointed out that this is the wrong name for this mythological figure. We reviewed the archive to see where this tag was used and it was used incorrectly anyway. All those Alcmans were in fact the poet, so we can reject this one from the list to help us catch the bad ones when we validate persNames in old books.

**Comment by brclar15** [comment]
pers265 has been rejected in the auth list, and redirected to Alcman the choral poet
