### ISSUE TITLE
New place: Pergamus, 324v

### ISSUE THREAD

**Issue by zachsowerby** [homermultitext/hmt-authlists#423]
The citadel of Troy

urn:cts:greekLit:tlg0012.tlg001.msA:24.700

urn:cite:hmt:vaimg.VA324VN-0826@0.473,0.5781,0.421,0.0248

**Comment by brclar15** [comment]
ooo I'm pretty sure this is not tagged..... like the Scaean gates. OR we tag it to place6. I'll check and get back to you

**Comment by zachsowerby** [comment]
Ok. Just curious - if not, why not?

**Comment by brclar15** [comment]
Ok so we do NOT tag Pergamus. It's just a certain part of Troy (but also not Troy itself), like the gates or the oak tree on the Trojan plain. This is just the level of specificity that we use for the tags. 
good question though!
