### ISSUE TITLE
New persName: Aretades, 313r

### ISSUE THREAD

**Issue by zachsowerby** [homermultitext/hmt-authlists#426]
of Cnidus, author and historian

Main scholion urn:cts:greekLit:tlg5026.msA.hmt:24.X4

urn:cite2:hmt:vaimg.2017a:VA313RN_0483@0.6562,0.3888,0.1982,0.1432

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:24.110

**Comment by brclar15** [comment]
added as urn:cite2:hmt:pers:pers1142
