### ISSUE TITLE
What to do with the Myrmidons

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#433]
210r line 220: Μυρμιδόνων
How do we tag the Myrmidons? We have checked previous occurences--these were left untagged. We want to check if this is ok.
urn:cts:greekLit:tlg0012.tlg001:16.220

**Comment by brclar15** [comment]
we do in fact leave the Myrmidons untagged. The rationale behind this is that we can't really tie them to an eponymous ancestor//homeland. 

hope all is well!
