### ISSUE TITLE
209r line 16.173-175 - Proposal for names not yet in the pers list

### ISSUE THREAD

**Issue by SEBoreel** [homermultitext/hmt-authlists#435]
We have encountered three names on 209r that are not yet on the pers list:

16.173:
Μενεσθιός = Son of Spercheios and Polydore, ... of the Mirmydones

16.174:
Σπερχειοῖο = River in Thessaly and rivergod of that name, father of Menesthios

16.175:
Πολυδώρη = Daughter of Peleus, wife of Boros, mother of Menesthios (with Spercheios as father)

Could you add them, please?
Thank you!

**Comment by brclar15** [comment]
added as : 
urn:cite2:hmt:pers:pers1146 - Menesthius
urn:cite2:hmt:pers:pers1147 - Polydora
urn:cite2:hmt:pers:pers1148 - Spercheus  (Note: make sure to check the placeName of the river itself if it comes up in the scholia)
