### ISSUE TITLE
New persName Hermeias 210r

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#437]
Main scholion urn:cts:greekLit:tlg5026.msA.hmt:16.210r3
urn:cite2:hmt:vaimg.2017a:VA210RN_0381@0.5063,0.1546,0.1113,0.02241

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:16.207

Hermeias from the school of Crates (Hermeias ὁ Κρατήτειος)
This is the sole occurrence of Hermeias in the Venetus A.

**Comment by DocTaz** [comment]
N.B. Hermeias occurs in the Iliad text too (hence, there is an entry in the AuthList), but this is obviously not the same "person".

**Comment by brclar15** [comment]
added as urn:cite2:hmt:pers:pers1150 for Hermeias, the scholar in the school of Crates
