### ISSUE TITLE
New PersName Dodona the Oceanid 210v

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#438]
Main scholion urn:cts:greekLit:tlg5026.msA.hmt:16.210v1
urn:cite2:hmt:vaimg.2017a:VA210VN_0712@0.4250,0.1663,0.1883,0.01383

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:16.233

2 issues:
(1) This scholion explores the aetiology and etymology of "Dodonean" Zeus. "Dodona" occurs several times as placeName, but here a "daughter of Oceanus" is mentioned with the name Dodona (after whom the place Dodona is, allegedly, named).
(2) How do we tag "Oceanid"? It is a patronymic, but not a uniquely identifying one (such as Peleiad), but one that signifies a group (like "Priam's sons").

**Comment by brclar15** [comment]
Ok, I've added Dodona the Oceanid as urn:cite2:hmt:pers:pers1151

the part about tagging Oceanid is an excellent question! I'll do some digging and get back to you

**Comment by zachsowerby** [comment]
Nope on the Oceanids
