### ISSUE TITLE
New PersName Thrasyboulos & Acestodoros 210v

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#440]
Main scholion urn:cts:greekLit:tlg5026.msA.hmt:16.210v1
urn:cite2:hmt:vaimg.2017a:VA210VN_0712@0.2367,0.1675,0.7167,0.02877

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:16.233
2 mystery grammarians are being mentioned here: Thrasyboulos and Acestodoros.
Both are hapaxes in the Venetus A.
Both grammarians are mentioned in Herodianus, de prosodia catholica (Grammatici Graeci 3.1 p.336).

**Comment by zachsowerby** [comment]
Thanks Professor,
Thrasybulus has been added as urn:cite2:hmt:pers.v1:pers1153, and Acestodorus as urn:cite2:hmt:pers.v1:pers1153.
