### ISSUE TITLE
Missing names in authlist 

### ISSUE THREAD

**Issue by OVRMonster** [homermultitext/hmt-authlists#441]
Amphiclon (16.313) 
Atymnios (16.317) 
Maris (16.319) 

These names have no entry.

**Comment by zachsowerby** [comment]
Thanks Olivia,

Amphiclus added as _urn:cite2:hmt:pers.v1:pers1155_;
Atymnius added as _urn:cite2:hmt:pers.v1:pers1156_;
Maris added as _urn:cite2:hmt:pers.v1:pers1157_.
