### ISSUE TITLE
New PersName Hellos the Woodcutter 210v

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#443]
Main scholion urn:cts:greekLit:tlg5026.msA.hmt:16.210v5
urn:cite2:hmt:vaimg.2017a:VA210VN_0712@0.2393,0.4409,0.09267,0.01051

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:16.234
Hellos the Woodcutter, allegedly the eponymous ancestor of the Helloi.
(Also mentioned in Philostratus the Elder, Imagines 2.33.1)

**Comment by zachsowerby** [comment]
Thanks Professor,

Added as _urn:cite2:hmt:pers.v1:pers1158_
