### ISSUE TITLE
New PersName Alexander of Pleuron 210v

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#444]
Main scholion urn:cts:greekLit:tlg5026.msA.hmt:16.210v7
urn:cite2:hmt:vaimg.2017a:VA210VN_0712@0.2235,0.6586,0.2192,0.02725

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:16.235
Alexander of Pleuroon (in Aeotolia), fl. around 280 BC

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1159_.

Thanks!
