### ISSUE TITLE
What to do with Turrhenoi?

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#445]
Main scholion urn:cts:greekLit:tlg5026.msA.hmt:16.210v7
urn:cite2:hmt:vaimg.2017a:VA210VN_0712@0.2859,0.6827,0.04606,0.01604

Commenting on Iliad line urn:cts:greekLit:tlg0012.tlg001.msA:16.235
Tyrrhenoi (the Etruscans): etymology uncertain, so we do not have an eponymous ancestor nor a placeName to anchors this name in. So no tagging?

**Comment by brclar15** [comment]
Ah tricky question. I think we can tag it to Etruria and avoid the ancient debate

added as    urn:cite2:hmt:place.v1:place470
