### ISSUE TITLE
New PersNames on 209r main scholia

### ISSUE THREAD

**Issue by SEBoreel** [homermultitext/hmt-authlists#448]
On folio 209r of the Venetus A in main scholion 7 (urn:cite2:hmt:vaimg.2017a:VA209RN_0380@0.1783,0.7748,0.6349,0.03416), we found several names that are currently not in the auth lists:

Stamphylos: Staphylos from Naukratis, writer (NB: the extra m is not a typo on our side, we found it like this in the scholion)

Thessalikon: a work written by Staphylos from Naukratis (Greek: Θεσσαλικῶν)

Eurydike: daughter of Actor

Actor: father of Eurydike

Antigone: daughter of Eurytion

Eurytion: father of Antigone

Laodameia: daughter of Alkmaion

Alkmaion: father of Laodemia

**Comment by zachsowerby** [comment]
Thessalica added as _urn:cite2:hmt:citedworks:work5_

Eurydice added as _urn:cite2:hmt:pers.v1:pers1162_

Actor added as _urn:cite2:hmt:pers.v1:pers1163_

Antigone added as _urn:cite2:hmt:pers.v1:pers1164_

Eurytion added as _urn:cite2:hmt:pers.v1:pers1165_

Laodamia added as _urn:cite2:hmt:pers.v1:pers1166_

Alcmaeon added as _urn:cite2:hmt:pers.v1:pers1167_

Staphylus of Naucratis added as _urn:cite2:hmt:pers.v1:pers1168_


Thanks!
