### ISSUE TITLE
209v PersNames

### ISSUE THREAD

**Issue by Bijvoets** [homermultitext/hmt-authlists#449]
Venetus A 206v (Iliad 16.176-200) contains several names not yet included in the person list:

* Eudorus (179): a Myrmidon, son of Argeiphontes and Polymele
* Polymele (180): daughter of Phylas and mother of Eudoros
* Phylas (181): father of Polymele
* Argeiphontes (181): father of Eudorus
* Echecles (189): son of Actor and husband of Polymele
* Peisander (193): a Myrmidon, son of Maemalus
* Maemalus (194): father of Peisander

**Comment by zachsowerby** [comment]
Thanks Bart,
Eudorus added as _urn:cite2:hmt:pers.v1:pers1169_

Polymele added as _urn:cite2:hmt:pers.v1:pers1170_

Phylas added as _urn:cite2:hmt:pers.v1:pers1171_

Echecles added as _urn:cite2:hmt:pers.v1:pers1172_

Peisander added as _urn:cite2:hmt:pers.v1:pers1173_

Argeiphontes is an epithet of Hermes, so a new entry was not added. Maemalus only appears as part of a patronymic, which is not marked up and therefore a new entry was not added.
