### ISSUE TITLE
208v how to mark up Μασσαλιωτική?

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#452]
interior scholion on 16.127: mentions the Μασσαλιωτική
Do we have a way of marking up different ekdoseis? Or do we mark this up as referring to a geographical entity (Massalia)?

**Comment by brclar15** [comment]
you can mark it with a title element, without any geographic tag or anything like that.
We haven't done anything more with titles yet, so no need for any attributes on it, just the <title>
