### ISSUE TITLE
New PersName: Thrasymelus

### ISSUE THREAD

**Issue by KirstenHaijes** [homermultitext/hmt-authlists#464]
## Example
Folio 215r, book 16 line 463.
-   Image  illustrating the passage:    urn:cite2:hmt:vaimg.2017a:VA215RN_0386@0.4711,0.4149,0.1225,0.02379

##  DIscussion
-  Thrasymelus
-  A servant of Sarpedon

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1181_

Thanks!
