### ISSUE TITLE
New Persname: Thrasydemos

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#465]
## Example
- urn:cts:greekLit:tlg5026.msAim.hmt:16.215r.2
- rn:cite2:hmt:msA.v1:215r
- urn:cite2:hmt:vaimg.2017a:VA215RN_0386@0.7220,0.4480,0.08143,0.01729

##  DIscussion
- Thrasydemos
- warrior, fighting on the Trojan side
- N.B. main text says Thrasymelos

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1181_

We are treating this as a multiform name for Thrasymelus.

Thanks!
