### ISSUE TITLE
New Persname Erymas

### ISSUE THREAD

**Issue by PhilipMuijtjens** [homermultitext/hmt-authlists#466]
Example 

- urn:cite2:hmt:vaimg.2017a:VA212VN_0714@0.5094,0.5823,0.4493,0.03043
- urn:cite2:hmt:vaimg.2017a:VA212VN_0714
- urn:cite2:hmt:vaimg.2017a:VA212VN_0714@0.6417,0.5812,0.1054,0.02656

Discussion

- Erymas
- He was a Trojan. He was speared through the mouth and subsequently killed by Idomeneus.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1182_

Thanks!
