### ISSUE TITLE
New Personal Name: Agacleos

### ISSUE THREAD

**Issue by MarloesVelthuisen** [homermultitext/hmt-authlists#467]
-   urn:cts:greekLit:tlg5026.msAim.hmt:16.215r.20
-   rn:cite2:hmt:msA.v1:217r
-   urn:cite2:hmt:vaimg.2017a:VA217RN_0388@0.2327,0.5602,0.09119,0.02213

- Agacleos
-  father of Epeigeus

**Comment by zachsowerby** [comment]
Added as Agacles, _urn:cite2:hmt:pers.v1:pers1183_

Thanks!
