### ISSUE TITLE
New Personal Name: Epegeus

### ISSUE THREAD

**Issue by MarloesVelthuisen** [homermultitext/hmt-authlists#468]
-   urn:cts:greekLit:tlg5026.msAim.hmt:16.215r.20
-   rn:cite2:hmt:msA.v1:217r
-   urn:cite2:hmt:vaimg.2017a:VA217RN_0388@0.4722,0.5602,0.07903,0.02351

-  Epegeus
-  King of Budeum

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1184_

Thanks!
