### ISSUE TITLE
Add new Name: Pronoös

### ISSUE THREAD

**Issue by ManonJunggeburt** [homermultitext/hmt-authlists#469]
## Example

-   urn:cite2:hmt:vaimg.2017a:VA213VN_0715@0.4799,0.6391,0.4134,0.02462
-   urn:cite2:hmt:vaimg.2017a:VA213VN_0715
-   urn:cite2:hmt:vaimg.2017a:VA213VN_0715@0.5709,0.6422,0.08014,0.01757

##  Discussion

-  Pronoös
-  Pronoös was killed by Patroclus

**Comment by zachsowerby** [comment]
Added as Pronous, _urn:cite2:hmt:pers.v1:pers1185_

Thanks!
