### ISSUE TITLE
New Geographical name: Budeum

### ISSUE THREAD

**Issue by MarloesVelthuisen** [homermultitext/hmt-authlists#470]
urn:cts:greekLit:tlg5026.msAim.hmt:16.215r.21
rn:cite2:hmt:msA.v1:217r
urn:cite2:hmt:vaimg.2017a:VA217RN_0388@0.2526,0.5784,0.09193,0.02144

-  Budeum

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:place.v1:place463_

Thanks!
