### ISSUE TITLE
New Persname: Erymas

### ISSUE THREAD

**Issue by PhilipMuijtjens** [homermultitext/hmt-authlists#471]
Example

-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.1852,0.4405,0.4206,0.02918
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.2937,0.4447,0.08990,0.02061

DIscussion

-  Erymas
-  He was a Trojan warrior. He was killed by Patroclus.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1186_

Thanks!
