### ISSUE TITLE
Add new name: Thestor

### ISSUE THREAD

**Issue by ManonJunggeburt** [homermultitext/hmt-authlists#472]
## Example

-   urn:cite2:hmt:vaimg.2017a:VA213VN_0715@0.4757,0.6758,0.4005,0.02669
-   urn:cite2:hmt:vaimg.2017a:VA213VN_0715
-   urn:cite2:hmt:vaimg.2017a:VA213VN_0715@0.7017,0.6773,0.06098,0.01950

##  Discussion

-  Thestor
-  He is the son of Enops. He was killed by Patroclus.

**Comment by zachsowerby** [comment]
Thestor added as _urn:cite2:hmt:pers.v1:pers1174_
