### ISSUE TITLE
New Persname: Amphoteros

### ISSUE THREAD

**Issue by PhilipMuijtjens** [homermultitext/hmt-authlists#474]
Example

-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.1815,0.4423,0.4237,0.02697
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.4213,0.4472,0.08990,0.02102

DIscussion

-  Amphoteros
-  A Trojan warrior.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1188_

Thanks!
