### ISSUE TITLE
New Persname: Erylaos

### ISSUE THREAD

**Issue by PhilipMuijtjens** [homermultitext/hmt-authlists#475]
Example

-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.1887,0.3672,0.4033,0.02642
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.3043,0.3698,0.08419,0.02158

Discussion

-  Euryalos (cf. 16.411; f. 241r)
-  A Trojan warrior.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1189_

Thanks!
