### ISSUE TITLE
New personal name: Sthenelaos

### ISSUE THREAD

**Issue by SEBoreel** [homermultitext/hmt-authlists#476]
## Example

-   Passage where the name occurs: urn:cite2:hmt:vaimg.2017a:VA217VN_0719@0.4853,0.3896,0.3906,0.02822
-   Page reference:  urn:cite2:hmt:vaimg.2017a:VA217VN_0719
-   Image  illustrating the passage: urn:cite2:hmt:vaimg.2017a:VA217VN_0719@0.5967,0.3959,0.09488,0.01853

##  Discussion

-  Sthenelaos
-  Son of Ithaimenes, killed by Patroclus

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1190_

Thanks!
