### ISSUE TITLE
New personal name: Ithaimenes

### ISSUE THREAD

**Issue by SEBoreel** [homermultitext/hmt-authlists#477]
## Example

-   Passage where the name occurs: urn:cite2:hmt:vaimg.2017a:VA217VN_0719@0.4853,0.3896,0.3906,0.02822
-   Page reference: urn:cite2:hmt:vaimg.2017a:VA217VN_0719
-   Image  illustrating the passage: urn:cite2:hmt:vaimg.2017a:VA217VN_0719@0.6925,0.3936,0.1057,0.02144

##  Discussion

-  Ithaimenes
-  Person from Lycia, father of Sthenelaos

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1191_

Thanks!
