### ISSUE TITLE
New Persname: Epaltês

### ISSUE THREAD

**Issue by PhilipMuijtjens** [homermultitext/hmt-authlists#478]
Example

-  urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.1848,0.4396,0.4208,0.02960
-  urn:cite2:hmt:vaimg.2017a:VA214RN_0385
-  urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.5350,0.4459,0.07038,0.02517

Discussion

-  Epaltês
-  Lycian warrior. Killed by Patroclus.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1192_

Thanks!
