### ISSUE TITLE
New Persname: Tlepolemos

### ISSUE THREAD

**Issue by PhilipMuijtjens** [homermultitext/hmt-authlists#479]
Example

-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.1805,0.4621,0.1229,0.02517
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.1811,0.4629,0.4118,0.02490

Discussion

-  Tlepolemos
-  A Trojan warrior. Son of Damastor. Killed by Patroclus. Not to be confused with Tlepolemos son of Heracles.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1199_

Thanks!
