### ISSUE TITLE
New personal name: Bathycles

### ISSUE THREAD

**Issue by SEBoreel** [homermultitext/hmt-authlists#480]
## Example

-   Passage where the name occurs:  urn:cite2:hmt:vaimg.2017a:VA217VN_0719
-   Page reference: urn:cite2:hmt:vaimg.2017a:VA217VN_0719
-   Image illustrating the passage: urn:cite2:hmt:vaimg.2017a:VA217VN_0719

##  Discussion

-  Bathycles
-  Myrmidon, killed by Patroclus

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1200_

Thanks!
