### ISSUE TITLE
New Persname: Damastor

### ISSUE THREAD

**Issue by PhilipMuijtjens** [homermultitext/hmt-authlists#481]
Example

-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.1811,0.4629,0.4118,0.02490
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.3222,0.4633,0.1266,0.02241

Discussion

-  Damastorides ("son of Damastor)
-  A Trojan warrior. Father of Tlepolemos.

**Comment by zachsowerby** [comment]
As this is a patronymic, it is marked with the persName of the son, not the father.

Thanks!
