### ISSUE TITLE
New Persname: Echios

### ISSUE THREAD

**Issue by PhilipMuijtjens** [homermultitext/hmt-authlists#482]
Example

-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.1778,0.4609,0.4154,0.02766
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.4499,0.4664,0.05306,0.02089

Discussion

-  Echios
-  A Lycian warrior. Killed by Patroclus.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1201_

Thanks!
