### ISSUE TITLE
New Persname: Polymelos

### ISSUE THREAD

**Issue by PhilipMuijtjens** [homermultitext/hmt-authlists#485]
Example

-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.1863,0.4826,0.3970,0.02517
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.4694,0.4845,0.1109,0.02324

Discussion

-  Polymêlos
-  Lykian warrior, killed by Patroclus.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1205_

Thanks!
