### ISSUE TITLE
New Persname: Argeas

### ISSUE THREAD

**Issue by PhilipMuijtjens** [homermultitext/hmt-authlists#486]
Example

-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.1863,0.4826,0.3970,0.02517
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385
-   urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.3863,0.4842,0.08714,0.02006

Discussion

-  Argeas
-  Father of Polymelos.

**Comment by zachsowerby** [comment]
As this is a patronymic, it is marked with the persName tag of the son.

Thanks!
