### ISSUE TITLE
Sequence of personal names

### ISSUE THREAD

**Issue by MarloesVelthuisen** [homermultitext/hmt-authlists#487]
urn:cts:greekLit:tlg5026.msAim.hmt:16.219v.14-16
rn:cite2:hmt:msA.v1:219v
urn:cite2:hmt:vaimg.2017a:VA219VN_0721@0.4818,0.4722,0.4123,0.05214

Multiple names: Adrastus, Autonous, Echeclus, Perimus, Epistor, Melanippus, Elasus, Moulius. Pylartes

**Comment by zachsowerby** [comment]
Adrastus added as _urn:cite2:hmt:pers.v1:pers1206_

Autonous added as _urn:cite2:hmt:pers.v1:pers1207_


Echeclus added as _urn:cite2:hmt:pers.v1:pers1208_

Perimus added as _urn:cite2:hmt:pers.v1:pers1209_

Epistor added as _urn:cite2:hmt:pers.v1:pers1210_

Melanippus added as _urn:cite2:hmt:pers.v1:pers1211_

Elasus added as _urn:cite2:hmt:pers.v1:pers1212_

Mulius added as _urn:cite2:hmt:pers.v1:pers1213_

Pylartes added as _urn:cite2:hmt:pers.v1:pers1214_

Thanks!
