### ISSUE TITLE
New PersName Theron of Acragas

### ISSUE THREAD

**Issue by DocTaz** [homermultitext/hmt-authlists#488]
## Example

-   urn:cts:greekLit:tlg5026.msAim.hmt:16.216v4.
-   urn:cite2:hmt:msA.v1:216v
- urn:cite2:hmt:vaimg.2017a:VA216VN_0718@0.7106,0.7231,0.1422,0.01646

##  DIscussion

-  **Theron of Akragas**
-  5th-century politician, mentioned in Pindar, Olympian Odes 2 and 3

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1218_

Thanks!
