### ISSUE TITLE
New Personal Name: Megacleides

### ISSUE THREAD

**Issue by MarloesVelthuisen** [homermultitext/hmt-authlists#489]
## Example

urn:cts:greekLit:tlg5026.msAim.hmt:16.208v
rn:cite2:hmt:msA.v1:208v
urn:cite2:hmt:vaimg.2017a:VA208VN_0710@0.2502,0.5878,0.1940,0.02476

-  Megacleides

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1215_

Thanks!
