### ISSUE TITLE
two personal names: Aello, Okupete.

### ISSUE THREAD

**Issue by MarloesVelthuisen** [homermultitext/hmt-authlists#490]
## Example

urn:cts:greekLit:tlg5026.msAim.hmt:16.208v
rn:cite2:hmt:msA.v1:208v
urn:cite2:hmt:vaimg.2017a:VA208VN_0710@0.7835,0.7657,0.09009,0.01480

Aello, Okupete

**Comment by zachsowerby** [comment]
Aello added as _urn:cite2:hmt:pers.v1:pers1216_

Okypete added as _urn:cite2:hmt:pers.v1:pers1217_

Thanks Marloes!
