### ISSUE TITLE
new name: Forados

### ISSUE THREAD

**Issue by MarloesVelthuisen** [homermultitext/hmt-authlists#491]
urn:cts:greekLit:tlg5026.msAim.hmt:16.208v
rn:cite2:hmt:msA.v1:208v
urn:cite2:hmt:vaimg.2017a:VA208VN_0710@0.5251,0.7833,0.04477,0.01563

Forados

**Comment by zachsowerby** [comment]
Thanks Marloes,

This is a grammatical example in the scholion and does not refer to a person, so we put it in a q tag rather than a persName tag. (Hi from the States!)
