### ISSUE TITLE
Boetia

### ISSUE THREAD

**Issue by zachsowerby** [homermultitext/hmt-authlists#497]
## Example

-   urn:cts:greekLit:tlg5026.msA.hmt:20.267v_4
-   urn:cite2:hmt:msA.v1:267v
-  urn:cite2:hmt:vaimg.2017a:VA267VN_0769@0.2135,0.4791,0.2332,0.08188
##  DIscussion

- Boetia
- Region of Greece located north of Attica on the Gulf of Corinth.

**Comment by neelsmith** [comment]
Rejected.  Duplicate with urn:cite2:hmt:place.v1:place30
