### ISSUE TITLE
Candaules

### ISSUE THREAD

**Issue by jngarr20** [homermultitext/hmt-authlists#502]
## Example

-   urn:cite2:greekLit:tlg5026.msA.hmt:267v3
-   urn:cite2:hmt:msA.v1:267v
-   urn:cite2:hmt:vaimg.2017a:VA267VN_0769@0.2015,0.4124,0.2620,0.07455

##  DIscussion

-  Candaules
-  Last King of the Lydian Heraclid dynasty, killed by Gyges.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1229_

Thanks!
