### ISSUE TITLE
Hyllus River

### ISSUE THREAD

**Issue by jngarr20** [homermultitext/hmt-authlists#505]
## Example

-   urn:cts:greekLit:tlg0012.tlg001.msA.2017a:20.392
-   urn:cite2:hmt:msA.v1:267v
-   urn:cite2:hmt:vaimg.2017a:VA267VN_0769@0.4753,0.4285,0.3721,0.02918

##  DIscussion

-  **Hyllus River**
-  A tributary of the Hermus River which runs through Lydia.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:place.v1:place465_

Thanks!
