### ISSUE TITLE
Iphition

### ISSUE THREAD

**Issue by jngarr20** [homermultitext/hmt-authlists#507]
## Example

-  urn:cts:greekLit:tlg0012.tlg001.msA.2017a:20.382
-   urn:cite2:hmt:msA.v1:267v
-   urn:cite2:hmt:vaimg.2017a:VA267VN_0769@0.4689,0.2441,0.4294,0.02476

##  DIscussion

-  **Iphition**
-  Son of Otrunteus, slain by Achilles.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1230_

Thanks!
