### ISSUE TITLE
Otrunteus

### ISSUE THREAD

**Issue by jngarr20** [homermultitext/hmt-authlists#508]
## Example

-   urn:cts:greekLit:tlg0012.tlg001.msA.2017a:20.384
-   urn:cite2:hmt:vaimg.2017a:VA267VN_0769@0.4696,0.2817,0.4193,0.01936
-   urn:cite2:hmt:msA.v1:267v

##  DIscussion

-  Otrunteus
-  King of Hyde, father of Iphition

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1231_

Thanks!
