### ISSUE TITLE
Demouchos

### ISSUE THREAD

**Issue by jgarry98** [homermultitext/hmt-authlists#510]
## Example

-   urn:cts:greekLit:tlg0012.tlg001.msA.2017a:20.457
-   urn:cite2:hmt:vaimg.2017a:VA269RN_0439@0.2006,0.2055,0.4016,0.02960
-   urn:cite2:hmt:msA.v1:269r
##
##  DIscussion

-  Demouchos
-  Trojan, son of Philetor.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1232_

Thanks!
