### ISSUE TITLE
Agelaos

### ISSUE THREAD

**Issue by jgarry98** [homermultitext/hmt-authlists#514]
## Example

-urn:cts:greekLit:tlg5026.msA.hmt:20.269r_2 
 -urn:cite2:hmt:vaimg.2017a:VA269RN_0439@0.6328,0.3225,0.1982,0.2790   
 -urn:cite2:hmt:msA.v1:269r
##  DIscussion

-  Agelaos
-  Suitor of Penelope, son of Damastor, killed by Odysseus.

**Comment by zachsowerby** [comment]
Added _urn:cite2:hmt:pers.v1:pers1243_

Thanks!
