### ISSUE TITLE
Rhigmus

### ISSUE THREAD

**Issue by jgarry98** [homermultitext/hmt-authlists#515]
## Example
urn:cts:greekLit:tlg0012.tlg001.msA.2017a:20.485
urn:cite2:hmt:vaimg.2017a:VA269VN_0771@0.4873,0.3019,0.3943,0.02531
urn:cite2:hmt:msA.v1:269v

##  DIscussion

-  Rhigmus
-  Son of Peirous,Thracian slain by Achilles.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1244_

Thanks!
