### ISSUE TITLE
Areitheos

### ISSUE THREAD

**Issue by jgarry98** [homermultitext/hmt-authlists#516]
## Example
urn:cts:greekLit:tlg0012.tlg001.msA.2017a:20.487
urn:cite2:hmt:vaimg.2017a:VA269VN_0771@0.4832,0.3386,0.3804,0.02517
urn:cite2:hmt:msA.v1:269v

##  DIscussion

- Areitheos
- Attendant to Rhigmus, killed by Achilles.

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1245_

Thanks!
