### ISSUE TITLE
Demolion

### ISSUE THREAD

**Issue by jgarry98** [homermultitext/hmt-authlists#517]
## Example

urn:cts:greekLit:tlg0012.tlg001.msA.2017a:20.395
urn:cite2:hmt:vaimg.2017a:VA267VN_0769@0.4753,0.4859,0.4001,0.02462
urn:cite2:hmt:msA.v1:267v

##  DIscussion

-  **Demolion**
-  Son of Antenor

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1246_

Thanks!
