### ISSUE TITLE
Hippodamus

### ISSUE THREAD

**Issue by jgarry98** [homermultitext/hmt-authlists#518]
## Example

urn:cts:greekLit:tlg0012.tlg001.msA.2017a:20.401
urn:cite2:hmt:vaimg.2017a:VA267VN_0769@0.4854,0.6017,0.4129,0.02379
urn:cite2:hmt:msA.v1:267v

##  DIscussion

-  **Hippodamas*
-  Trojan slain by Achilles

**Comment by zachsowerby** [comment]
Added as _urn:cite2:hmt:pers.v1:pers1247_

Thanks!
