### ISSUE TITLE
Leleges

### ISSUE THREAD

**Issue by KirstenHaijes** [homermultitext/hmt-authlists#524]
## Example

-   Passage where the name occurs:  10.429
-   Page reference:  urn:cite2:hmt:vbbifolio.v1:vb_137v_138r
-   Image  illustrating the passage:  urn:cite2:hmt:vbbifolio.v1:vb_137v_138r@0.5337,0.5829,0.03519,0.02542

##  DIscussion

-  Leleges
-  Tribe settled in the southern Troad around Pedasus and Lyrnessus.

**Comment by zachsowerby** [comment]
Hello Kirsten,

It looks like the project uses the eponymous founder, Lelex, in the `<rs>` tag (`urn:cite2:hmt:pers.v1:pers777`).

Thanks!

Zach Sowerby
