### ISSUE TITLE
Maeonia

### ISSUE THREAD

**Issue by KirstenHaijes** [homermultitext/hmt-authlists#525]
## Example

-   Passage where the name occurs:  10.431
-   Page reference: urn:cite2:hmt:vbbifolio.v1:vb_137v_138r
-   Image  illustrating the passage:  urn:cite2:hmt:vbbifolio.v1:vb_137v_138r@0.6365,0.6219,0.03924,0.02394

##  Discussion

-  Maeonia
-  Area in Lydia.

**Comment by zachsowerby** [comment]
Hello Kirsten,

It looks like for the purposes of HMT Maeonia is identified as an alternative (older) name for Lydia (`urn:cite2:hmt:place.v1:place87`) and that this is the number that should be used in the rs tag.

Best,

Zach Sowerby
