### ISSUE TITLE
New Place Name: Egyptian Thebes

### ISSUE THREAD

**Issue by jgarry98** [homermultitext/hmt-authlists#526]
## Example

-   Passage where the name occurs:  **urn:cite2:greeklit:tlg0012.tlg001.e3:9.381**
-   Page reference: urn:cite2:hmt:e3bifolio.v1:E3_116v_117r
-   Image  illustrating the passage:  urn:cite2:hmt:e3bifolio.v1:E3_116v_117r@0.6564,0.6195,0.03668,0.02314

##  DIscussion

-  Thebes of Egypt
-  Distinguished from the two other cities called Thebes with the epithet "hundred-gated"

**Comment by brclar15** [comment]
added as urn:cite2:hmt:place.v1:place484
