### ISSUE TITLE
Lycomedes

### ISSUE THREAD

**Issue by zachsowerby** [homermultitext/hmt-authlists#527]
## Example

-   Passage where the name occurs:  **urn:cts:greekLit:tlg0012.tlg001:9.84**
-   Page reference:  **urn:cite2:hmt:burney86.v1:84v**
-   Image  illustrating the passage:    **urn:cite2:hmt:burney86.v1:burney_ms_86_f084v@0.5780,0.6356,0.1072,0.03077**

##  Discussion

-  **Lycomedes**
-  a son of Creon, one of the Greek warriors at Troy. (Not the king of Scyros, nor the Cretan suitor of Helen.)

**Comment by brclar15** [comment]
added as urn:cite2:hmt:pers.v1:pers1264
