### ISSUE TITLE
New persName: Iphianassa

### ISSUE THREAD

**Issue by lcgiuntoli** [homermultitext/hmt-authlists#528]
## Example

-   Passage where the name occurs:  urn:cts:greekLit:tlg0012.tlg001.e3:9.145
-   Page reference:  urn:cite2:hmt:e3.v1:109v
-   Image  illustrating the passage:    urn:cite2:hmt:e3bifolio.v1:E3_112v_113r@0.2172,0.3197,0.2096,0.03160

##  DIscussion

-  Iphianassa
-  daughter of Agamemnon; one of three daughters Agamemnon offers to Achilles

**Comment by brclar15** [comment]
added as 
urn:cite2:hmt:pers.v1:pers1266.
Professor Dué made the argument to keep Iphianassa and Iphegenia separate. a note was made in the auth list to preserve this decision for the future
