### ISSUE TITLE
New place Name: Καρδαμύλη

### ISSUE THREAD

**Issue by lcgiuntoli** [homermultitext/hmt-authlists#529]
## Example

-   Passage where the name occurs:  urn:cts:greekLit:tlg0012.tlg001.e3:9.150
-   Page reference:  urn:cite2:hmt:e3.v1:112v for folio/side
-   Image  illustrating the passage:    urn:cite2:hmt:e3bifolio.v1:E3_112v_113r@0.2159,0.4066,0.2154,0.02869 for image with region of interest

##  DIscussion

-  Cardamyle
-  a town in Messene; offered to Achilles by Agamemnon in book 9

**Comment by brclar15** [comment]
added as urn:cite2:hmt:place.v1:place477
