### ISSUE TITLE
New placeName: Ἄνθεια

### ISSUE THREAD

**Issue by lcgiuntoli** [homermultitext/hmt-authlists#533]
## Example

-   Passage where the name occurs:  urn:cts:greekLit:tlg0012.tlg001.e3:9.151
-   Page reference:  urn:cite2:hmt:e3.v1:112v for folio/side
-   Image  illustrating the passage:    urn:cite2:hmt:e3bifolio.v1:E3_112v_113r@0.2148,0.4207,0.2181,0.03659 for image with region of interest

##  DIscussion

-  Antheia
-  a town in Messene; offered to Achilles by Agamemnon in book 9

**Comment by brclar15** [comment]
urn:cite2:hmt:place.v1:place479
