### ISSUE TITLE
New placeName: Πήδασος

### ISSUE THREAD

**Issue by lcgiuntoli** [homermultitext/hmt-authlists#535]
## Example

-   Passage where the name occurs:  urn:cts:greekLit:tlg0012.tlg001.e3:9.152
-   Page reference:  urn:cite2:hmt:e3.v1:112v for folio/side
-   Image  illustrating the passage:   urn:cite2:hmt:e3bifolio.v1:E3_112v_113r@0.2151,0.4403,0.2150,0.03063for image with region of interest

##  DIscussion

-  Pedasus
-  a town in Messene; offered to Achilles by Agamemnon in book 9

**Comment by brclar15** [comment]
This could possibly by urn:cite2:hmt:place.v1:place266

there are two, Pedasus (Messenia)  and Pedasus (Mysia). Need to look back at instances of this placeURN in VA to see this new one is the same as place266 or not

**Comment by brclar15** [comment]
definitely not the one in Mysia (as you guys already knew)

added as urn:cite2:hmt:place.v1:place481

**Comment by brclar15** [comment]
actually no! upon further research, it is **urn:cite2:hmt:place.v1:place384** https://en.wikipedia.org/wiki/Methone_(Messenia)
