### ISSUE TITLE
New name: Αἴθη

### ISSUE THREAD

**Issue by lcgiuntoli** [homermultitext/hmt-authlists#536]
## Example

-   Passage where the name occurs:  urn:cts:greekLit:tlg5026.e3.hmt:9.e3_112v_6
-   Page reference:  urn:cite2:hmt:e3.v1:112v for folio/side
-   Image  illustrating the passage:    urn:cite2:hmt:e3bifolio.v1:E3_112v_113r@0.1027,0.2023,0.3319,0.03368 for image with region of interest

##  DIscussion

-  Aethe
-  mare of Agamemnon; leads Menelaus's chariot in book 23

**Comment by neelsmith** [comment]
Added with URN urn:cite2:hmt:pers.v1:pers1262
