### ISSUE TITLE
Ephorus

### ISSUE THREAD

**Issue by taposi20** [homermultitext/hmt-authlists#539]
## Example

-   Passage where the name occurs:  urn:cts:greekLit:tlg5026.e3.hmt:9.e3_117r_16
-   Page reference:  urn:cite2:hmt:e3.v1:117r
-   Image  illustrating the passage:    urn:cite2:hmt:e3bifolio.v1:E3_116v_117r@0.5104,0.8045,0.02116,0.02162 
for image with region of interest

##  DIscussion

-  Ephorus
-  Greek historian

**Comment by brclar15** [comment]
added as urn:cite2:hmt:pers.v1:pers1298

(Hi Thomas!)
