### ISSUE TITLE
Add URN for Osiris 

### ISSUE THREAD

**Issue by lcgiuntoli** [homermultitext/hmt-authlists#540]
## Example

-   Passage where the name occurs:  urn:cts:greekLit:tlg5026.msB.hmt:9.msB_122v_1
-   Page reference:  **CITE2 URN** urn:cite2:hmt:msB.v1:122v
-   Image  illustrating the passage:    urn:cite2:hmt:vbbifolio.v1:vb_122v_123r@0.1509,0.1769,0.02819,0.01499

##  DIscussion

-  Osiris 
-  Legendary king of Egypt who fortified Thebes

**Comment by brclar15** [comment]
added as urn:cite2:hmt:pers.v1:pers1297
