### ISSUE TITLE
Diogenes

### ISSUE THREAD

**Issue by taposi20** [homermultitext/hmt-authlists#542]
## Example

-   Passage where the name occurs:  urn:cts:greekLit:tlg5026.e3.hmt:9.e3_118v_12
-   Page reference:  urn:cite2:hmt:e3bifolio.v1:E3_118v
-   Image  illustrating the passage:    urn:cite2:hmt:e3bifolio.v1:E3_118v_119r@0.2639,0.7087,0.02836,0.01774

##  DIscussion

-  Diogenes 
-  The cynic philosopher

**Comment by brclar15** [comment]
added as urn:cite2:hmt:pers.v1:pers1299
