### ISSUE TITLE
New dingbat: Tilted division sign

### ISSUE THREAD

**Issue by lcgiuntoli** [homermultitext/hmt-authlists#552]
Please include:

Resembles a tilted division sign. 

- urn:cite2:hmt:msB.v1:303v 
- urn:cite2:hmt:vbbifolio.v1:vb_303v_304r@0.09372,0.6562,0.009622,0.01299

**Comment by nadimattia** [comment]
We get this a ton in the Townley and we've been calling it the percent sign!

**Comment by lcgiuntoli** [comment]
> We get this a ton in the Townley and we've been calling it the percent sign!

That's a much better name!
