### ISSUE TITLE
New dingbat: Frowning Snail 

### ISSUE THREAD

**Issue by nadimattia** [homermultitext/hmt-authlists#592]
Please include:

- URN for a manuscript page where the dingbat occurs: urn:cite2:hmt:burney86pages.v1:250v
- Link to an example of the dingbat in the image citation tool: urn:cite2:citebl:burney86imgs.v1:burney_ms_86_f250v@0.7790,0.6920,0.06325,0.02819

**Comment by neelsmith** [comment]
Added as urn:cite2:hmt:dingbats.v1:dingbats30
